global:
  registry: localhost:5000

replicas: 1

# ── engines ───────────────────────────────
vllm:
  enabled: false
tgi:
  enabled: false
lorax:
  enabled: false
ollama:
  enabled: false

llamaCpp:
  enabled: true
  modelPath: /models/phi-3-mini-128k-instruct.Q4_K_M.gguf
  nGPULayers: 40
  threads: 12
  batch: 64

images:
  llamacpp: localhost:5000/zeno-llamacpp:latest  # Built locally by install script

modelVolume:
  hostPath: /zeno/models               # Overridden dynamically at install
  mountPath: /models