
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeno-agents
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: zeno-agents
  template:
    metadata:
      labels:
        app: zeno-agents
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: VLLM_ENDPOINT
              value: "http://zeno-inference:8000"
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: zeno-agents
spec:
  selector:
    app: zeno-agents
  ports:
    - port: 8001
      targetPort: 8001
